## 문제
- 도커 외부 포트를 통해 연결 시도시 아래와 같은 에러 발생
- ![image](https://user-images.githubusercontent.com/61215550/167341769-36b51367-46ff-4d8f-9b67-1ad8581adafe.png) 

## 해결 
- __도커 컴포즈__ 를 통해 연결 해결
